# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: da695dc35ad7849e71112ae88cd2f7ca854a6ae05604acdce3a1fe1bf7214b6fed0c5b05737d76dc4dd1cac0be624f182805ee151da2f130c5dea816f7665d60

test:
  secret_key_base: 58e4224d3505901328d123c1b407f3a9ff20a45572cdd453caab2fabaf730a3080ad2dbe104962428d7ea5cfbb76d4272a81cb5510da3cca26129d9a8a656dd9

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
